<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>genbu_ontology</name>
  <version>0.0.0</version>
  <description>Ontology package for the Genbu robot</description>
  <maintainer email="nnaraindev@gmail.com">Natesh Narain</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>robot_ontology_publisher</depend>
  <depend>sosa_ontology_vendor</depend>
  <depend>ament_robot_ontology</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
