site_name: Genbu Robot
site_description: Personal ROS development platform built on the iRobot Create 2
site_url: https://nnarain.github.io/genbu_robot

docs_dir: docs

theme:
  name: readthedocs
  logo: genbu-logo.png

markdown_extensions:
  - md_in_html

extra_css:
  - assets/styles/hardware.css

nav:
  - Home: index.md
  - Logs: logs/index.md
  - Hardware: hardware/index.md
  - Software: software/index.md
  - Simulation: simulation/index.md
