<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>genbu_bringup</name>
  <version>0.0.0</version>
  <description>Bringup for Genbu robot</description>
  <maintainer email="nnaraindev@gmail.com">Natesh Narain</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>create_bringup</depend>
  <depend>teleop_twist_joy</depend>
  <depend>ydlidar_ros2_driver</depend>
  <depend>genbu_navigation</depend>
  <depend>diagnostic_aggregator</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
