services:
  genbu-robot:
    image: ${GENBU_IMAGE:-ghcr.io/nnarain/genbu_robot:latest}
    container_name: genbu-robot
    network_mode: host
    privileged: true
    volumes:
      - /dev:/dev

  medkit-web-ui:
    image: ghcr.io/selfpatch/ros2_medkit_web_ui:latest
    container_name: ros2_medkit_web_ui
    ports:
      - "3000:80"
    restart: unless-stopped
