---
- name: Install Genbu Netplan recovery script
  ansible.builtin.copy:
    src: files/genbu-netplan-recovery.sh
    dest: /usr/local/bin/genbu-netplan-recovery.sh
    owner: root
    group: root
    mode: "0755"

- name: Install Genbu Netplan recovery systemd service
  ansible.builtin.copy:
    src: files/genbu-netplan-recovery.service
    dest: /etc/systemd/system/genbu-netplan-recovery.service
    owner: root
    group: root
    mode: "0644"

- name: Create /var/lib/genbu directory
  ansible.builtin.file:
    path: /var/lib/genbu
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Enable Genbu Netplan recovery service
  ansible.builtin.systemd:
    name: genbu-netplan-recovery
    daemon_reload: true
    enabled: true
